admin_user = "admin"
admin_email = "admin@test.com"
admin_password = "password"
default_avatar = "http://example.com/default_avatar.jpg"
addr = "0.0.0.0:8001"
db_url = "postgres://cong:password@localhost:5432/userservice"