// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthTokenReq) Reset()         { *m = AuthTokenReq{} }
func (m *AuthTokenReq) String() string { return proto.CompactTextString(m) }
func (*AuthTokenReq) ProtoMessage()    {}
func (*AuthTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *AuthTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthTokenReq.Unmarshal(m, b)
}
func (m *AuthTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthTokenReq.Marshal(b, m, deterministic)
}
func (m *AuthTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthTokenReq.Merge(m, src)
}
func (m *AuthTokenReq) XXX_Size() int {
	return xxx_messageInfo_AuthTokenReq.Size(m)
}
func (m *AuthTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthTokenReq proto.InternalMessageInfo

func (m *AuthTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthTokenResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthTokenResp) Reset()         { *m = AuthTokenResp{} }
func (m *AuthTokenResp) String() string { return proto.CompactTextString(m) }
func (*AuthTokenResp) ProtoMessage()    {}
func (*AuthTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *AuthTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthTokenResp.Unmarshal(m, b)
}
func (m *AuthTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthTokenResp.Marshal(b, m, deterministic)
}
func (m *AuthTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthTokenResp.Merge(m, src)
}
func (m *AuthTokenResp) XXX_Size() int {
	return xxx_messageInfo_AuthTokenResp.Size(m)
}
func (m *AuthTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthTokenResp proto.InternalMessageInfo

func (m *AuthTokenResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*AuthTokenReq)(nil), "protobuf.AuthTokenReq")
	proto.RegisterType((*AuthTokenResp)(nil), "protobuf.AuthTokenResp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0x2a, 0x5c,
	0x3c, 0x8e, 0xa5, 0x25, 0x19, 0x21, 0xf9, 0xd9, 0xa9, 0x79, 0x41, 0xa9, 0x85, 0x42, 0x22, 0x5c,
	0xac, 0x25, 0x20, 0xb6, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84, 0xa3, 0x24, 0xcf, 0xc5,
	0x8b, 0xa4, 0xaa, 0xb8, 0x40, 0x88, 0x8f, 0x8b, 0x29, 0x3f, 0x1b, 0xac, 0x86, 0x23, 0x88, 0x29,
	0x3f, 0xdb, 0xc8, 0x87, 0x8b, 0x25, 0xb4, 0x38, 0xb5, 0x48, 0xc8, 0x85, 0x8b, 0x3f, 0x2c, 0xb5,
	0x28, 0x33, 0xad, 0x12, 0xae, 0x5c, 0x48, 0x4c, 0x0f, 0x66, 0x99, 0x1e, 0xb2, 0x4d, 0x52, 0xe2,
	0x58, 0xc5, 0x8b, 0x0b, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x32, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x7b, 0x1f, 0x65, 0x8b, 0xb3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	VerifyAuthToken(ctx context.Context, in *AuthTokenReq, opts ...grpc.CallOption) (*AuthTokenResp, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) VerifyAuthToken(ctx context.Context, in *AuthTokenReq, opts ...grpc.CallOption) (*AuthTokenResp, error) {
	out := new(AuthTokenResp)
	err := c.cc.Invoke(ctx, "/protobuf.User/VerifyAuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	VerifyAuthToken(context.Context, *AuthTokenReq) (*AuthTokenResp, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) VerifyAuthToken(ctx context.Context, req *AuthTokenReq) (*AuthTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyAuthToken not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_VerifyAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).VerifyAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.User/VerifyAuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).VerifyAuthToken(ctx, req.(*AuthTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyAuthToken",
			Handler:    _User_VerifyAuthToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
